layout_spectrum: 0.35536979720927775
typography_spectrum: 0.22072647628374398
color:
  saturation: 0.3697307158727199
  brandStrength: 0.15673842024989426
  lightness: 0.15483069350011647
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  rhythmicContrast: 0.10247723804786801
title: Manipulated Images
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: For Sale
name: Photography
