title: Manipulated Images
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.173399664927274
  brandStrength: 0.2127102671656758
  rhythmicContrast: 0.1867188652977347
  brandColors:
    - '#170F0E'
    - '#290418'
    - '#505217'
    - '#FFD372'
    - '#FFF1AF'
  lightness: 0.1598520560655743
typography_spectrum: 0.2638298
description: For Sale
layout_spectrum: 0.3468085
name: Photography
